name: Custom
on:

  workflow_dispatch:
  push:
    branches: [ custom-action ]
  pull_request:
    branches: [ custom-action ]

jobs:
  main:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: kdahal/custom-action-data@main
